# Generated by Django 5.1.5 on 2025-02-02 17:08

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_alter_profile_age'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('due_date', models.DateTimeField(help_text='Краен срок с дата и час')),
                ('remaining', models.DurationField(blank=True, help_text='Оставащо време до крайния срок', null=True)),
                ('to_be_notified_on', models.DateTimeField(blank=True, default=datetime.datetime(2025, 2, 2, 17, 10, 3, 951246, tzinfo=datetime.timezone.utc), null=True)),
                ('status', models.CharField(choices=[('Done', 'Done'), ('Pending', 'Pending'), ('Overdue', 'Overdue')], default='Pending', max_length=100)),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_tasks', to='accounts.profile')),
            ],
        ),
    ]
