# Generated by Django 5.1.5 on 2025-02-02 17:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='to_be_notified_on',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 2, 2, 17, 12, 35, 374113, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
