# Generated by Django 5.1.5 on 2025-02-12 19:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks_app', '0008_alter_tasks_to_be_notified_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasks',
            name='remaining',
        ),
        migrations.AlterField(
            model_name='tasks',
            name='due_date',
            field=models.DateTimeField(help_text='Due date with time and hour'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='to_be_notified_on',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 2, 12, 19, 31, 59, 130768, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
