# Generated by Django 5.1.5 on 2025-02-12 20:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks_app', '0009_remove_tasks_remaining_alter_tasks_due_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='to_be_notified_on',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 2, 12, 20, 47, 34, 528218, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
