# Generated by Django 5.1.5 on 2025-02-12 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_profile_occupation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='occupation',
            field=models.CharField(default='unspecified', max_length=100),
        ),
    ]
