# Generated by Django 5.1.5 on 2025-01-26 11:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_tasks_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasks',
            name='time',
        ),
        migrations.AddField(
            model_name='tasks',
            name='due_time',
            field=models.TimeField(default=datetime.datetime(2025, 1, 26, 13, 57, 41, 520748)),
        ),
    ]
