# Generated by Django 5.1.5 on 2025-01-26 12:32

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_profile_age'),
        ('tasks', '0003_remove_tasks_time_tasks_due_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='accounts.profile'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='due_time',
            field=models.TimeField(default=datetime.datetime(2025, 1, 26, 15, 2, 1, 684661)),
        ),
    ]
