# Generated by Django 5.1.5 on 2025-01-26 17:33

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_profile_age'),
        ('tasks', '0004_tasks_profile_alter_tasks_due_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='due_time',
            field=models.TimeField(default=datetime.datetime(2025, 1, 26, 20, 3, 52, 496982)),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_tasks', to='accounts.profile'),
        ),
    ]
