# Generated by Django 5.1.5 on 2025-01-26 18:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_alter_tasks_due_time_alter_tasks_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='due_time',
            field=models.TimeField(default=datetime.datetime(2025, 1, 26, 21, 1, 24, 663529)),
        ),
    ]
