# Generated by Django 5.1.5 on 2025-01-27 09:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_tasks_completed_tasks_status_alter_tasks_due_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasks',
            name='done',
        ),
        migrations.AlterField(
            model_name='tasks',
            name='due_time',
            field=models.TimeField(default=datetime.datetime(2025, 1, 27, 12, 26, 33, 312957)),
        ),
    ]
