# Generated by Django 5.1.5 on 2025-01-27 10:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_remove_tasks_done_alter_tasks_due_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='due_time',
            field=models.TimeField(default=datetime.datetime(2025, 1, 27, 12, 30, 7, 365263)),
        ),
    ]
