# Generated by Django 5.1.5 on 2025-01-27 10:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_alter_tasks_due_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='due_time',
            field=models.TimeField(default=datetime.datetime(2025, 1, 27, 12, 31, 21, 694660)),
        ),
    ]
