# Generated by Django 5.1.5 on 2025-01-28 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_alter_tasks_due_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasks',
            name='completed',
        ),
        migrations.RemoveField(
            model_name='tasks',
            name='due_time',
        ),
        migrations.AddField(
            model_name='tasks',
            name='remaining',
            field=models.DurationField(blank=True, help_text='Оставащо време до крайния срок', null=True),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='due_date',
            field=models.DateTimeField(help_text='Краен срок с дата и час'),
        ),
    ]
